# Generated by Django 4.2 on 2023-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=10000, verbose_name='Текст поста')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_update', models.DateField(auto_now=True, null=True, verbose_name='Дата изменения записи')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['date_create'],
            },
        ),
    ]
